name: Build and deploy

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

env:
  DOTNET_VERSION: "5.0.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ DOTNET_VERSION }}

      - name: Build and Test
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test
          dotnet publish -c Release -o ./out

      - name: Upload to GitHib
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ./out
